name: Update module
on:
  workflow_dispatch:
  repository_dispatch:
    types: update
  schedule:
    - cron: '0 0 * * MON'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
      - name: Update module
        run: |
          git submodule update --init --recursive
          git submodule foreach --recursive git fetch --all
          git submodule foreach git reset --hard origin/master
      - uses: stefanzweifel/git-auto-commit-action@v4.15.1
        with:
          commit_message: Updated submodules
